package com.maisonneuve.music_playlist_manager.model;

public enum Genre {
    _3_STEP("3 step"),
    ACID_HOUSE("acid house"),
    ACID_ROCK("acid rock"),
    ACID_TECHNO("acid techno"),
    ACOUSTIC_COUNTRY("acoustic country"),
    ACOUSTIC_POP("acoustic pop"),
    ADULT_STANDARDS("adult standards"),
    AFRO_ADURA("afro adura"),
    AFRO_HOUSE("afro house"),
    AFRO_R_AND_B("afro r&b"),
    AFRO_TECH("afro tech"),
    AFROBEAT("afrobeat"),
    AFROBEATS("afrobeats"),
    AFROPIANO("afropiano"),
    AFROPOP("afropop"),
    AFROSWING("afroswing"),
    AGRONEJO("agronejo"),
    ALT_COUNTRY("alt country"),
    ALTERNATIVE_DANCE("alternative dance"),
    ALTERNATIVE_METAL("alternative metal"),
    ALTERNATIVE_POP("alternative pop"),
    ALTERNATIVE_R_AND_B("alternative r&b"),
    ALTERNATIVE_ROCK("alternative rock"),
    ALT("alté"),
    AMAPIANO("amapiano"),
    AMBIENT("ambient"),
    AMBIENT_FOLK("ambient folk"),
    AMERICANA("americana"),
    ANIME("anime"),
    ANIME_RAP("anime rap"),
    ANTI_FOLK("anti-folk"),
    AOR("aor"),
    ARABIC_HIP_HOP("arabic hip hop"),
    ARENA_ROCK("arena rock"),
    ARGENTINE_TRAP("argentine trap"),
    ARROCHA("arrocha"),
    ART_POP("art pop"),
    ART_ROCK("art rock"),
    AVANT_GARDE("avant-garde"),
    AZONTO("azonto"),
    BACHATA("bachata"),
    BALLROOM_VOGUE("ballroom vogue"),
    BANDA("banda"),
    BAROQUE_POP("baroque pop"),
    BASS_MUSIC("bass music"),
    BEDROOM_POP("bedroom pop"),
    BIG_BAND("big band"),
    BIG_BEAT("big beat"),
    BIG_ROOM("big room"),
    BLUEGRASS("bluegrass"),
    BLUES("blues"),
    BLUES_ROCK("blues rock"),
    BOLERO("bolero"),
    BOLLYWOOD("bollywood"),
    BONGO_FLAVA("bongo flava"),
    BOOM_BAP("boom bap"),
    BRAZILIAN_BASS("brazilian bass"),
    BRAZILIAN_FUNK("brazilian funk"),
    BRAZILIAN_PHONK("brazilian phonk"),
    BRAZILIAN_POP("brazilian pop"),
    BREAKBEAT("breakbeat"),
    BREAKCORE("breakcore"),
    BRITPOP("britpop"),
    BROOKLYN_DRILL("brooklyn drill"),
    C_POP("c-pop"),
    CCM("ccm"),
    CELTIC("celtic"),
    CELTIC_PUNK("celtic punk"),
    CELTIC_ROCK("celtic rock"),
    CHAMBER_MUSIC("chamber music"),
    CHANSON("chanson"),
    CHANSON_QU_B_COISE("chanson québécoise"),
    CHICAGO_DRILL("chicago drill"),
    CHICHA("chicha"),
    CHILDRENS_MUSIC("childrens music\"\""),
    CHILLSTEP("chillstep"),
    CHILLWAVE("chillwave"),
    CHINESE_HIP_HOP("chinese hip hop"),
    CHORAL("choral"),
    CHRISTIAN("christian"),
    CHRISTIAN_ALTERNATIVE_ROCK("christian alternative rock"),
    CHRISTIAN_COUNTRY("christian country"),
    CHRISTIAN_FOLK("christian folk"),
    CHRISTIAN_HIP_HOP("christian hip hop"),
    CHRISTIAN_POP("christian pop"),
    CHRISTIAN_ROCK("christian rock"),
    CHRISTMAS("christmas"),
    CLASSIC_BLUES("classic blues"),
    CLASSIC_COUNTRY("classic country"),
    CLASSIC_ROCK("classic rock"),
    CLASSIC_SOUL("classic soul"),
    CLASSICAL("classical"),
    CLASSICAL_PIANO("classical piano"),
    CLOUD_RAP("cloud rap"),
    COLD_WAVE("cold wave"),
    COLOMBIAN_POP("colombian pop"),
    COMEDY("comedy"),
    CONTEMPORARY_R_AND_B("contemporary r&b"),
    CORRIDO("corrido"),
    CORRIDOS_B_LICOS("corridos bélicos"),
    CORRIDOS_TUMBADOS("corridos tumbados"),
    COUNTRY("country"),
    COUNTRY_BLUES("country blues"),
    COUNTRY_HIP_HOP("country hip hop"),
    COUNTRY_POP("country pop"),
    COUNTRY_ROCK("country rock"),
    CRUNK("crunk"),
    CUMBIA_NORTE_A("cumbia norteña"),
    DANCE_POP("dance pop"),
    DANCEHALL("dancehall"),
    DANSK_POP("dansk pop"),
    DANSK_RAP("dansk rap"),
    DARK_POP("dark pop"),
    DARK_R_AND_B("dark r&b"),
    DARKWAVE("darkwave"),
    DEATHROCK("deathrock"),
    DEATHSTEP("deathstep"),
    DEEP_HOUSE("deep house"),
    DEMBOW("dembow"),
    DEMBOW_BELICO("dembow belico"),
    DESI("desi"),
    DESI_HIP_HOP("desi hip hop"),
    DESI_POP("desi pop"),
    DISCO("disco"),
    DJENT("djent"),
    DOO_WOP("doo-wop"),
    DOOM_METAL("doom metal"),
    DOWNTEMPO("downtempo"),
    DREAM_POP("dream pop"),
    DRIFT_PHONK("drift phonk"),
    DRILL("drill"),
    DRONE("drone"),
    DRUM_AND_BASS("drum and bass"),
    DRUMSTEP("drumstep"),
    DUB("dub"),
    DUBSTEP("dubstep"),
    EAST_COAST_HIP_HOP("east coast hip hop"),
    EASY_LISTENING("easy listening"),
    EBM("ebm"),
    EDM("edm"),
    EDM_TRAP("edm trap"),
    EGYPTIAN_HIP_HOP("egyptian hip hop"),
    EGYPTIAN_POP("egyptian pop"),
    EGYPTIAN_SHAABI("egyptian shaabi"),
    ELECTRO("electro"),
    ELECTRO_CORRIDOS("electro corridos"),
    ELECTRO_HOUSE("electro house"),
    ELECTRO_SWING("electro swing"),
    ELECTROCLASH("electroclash"),
    ELECTRONIC("electronic"),
    ELECTRONICA("electronica"),
    ELECTROPOP("electropop"),
    EMO("emo"),
    EMO_RAP("emo rap"),
    ENKA("enka"),
    EURODANCE("eurodance"),
    EUROPOP("europop"),
    EXOTICA("exotica"),
    EXPERIMENTAL("experimental"),
    FINNISH_ROCK("finnish rock"),
    FOLK("folk"),
    FOLK_METAL("folk metal"),
    FOLK_POP("folk pop"),
    FOLK_ROCK("folk rock"),
    FRENCH_HOUSE("french house"),
    FRENCH_INDIE_POP("french indie pop"),
    FRENCH_POP("french pop"),
    FRENCH_R_AND_B("french r&b"),
    FRENCH_RAP("french rap"),
    FUNK("funk"),
    FUNK_CARIOCA("funk carioca"),
    FUNK_CONSCIENTE("funk consciente"),
    FUNK_DE_BH("funk de bh"),
    FUNK_POP("funk pop"),
    FUNK_ROCK("funk rock"),
    FUNKOT("funkot"),
    FUTURE_BASS("future bass"),
    FUTURE_HOUSE("future house"),
    G_FUNK("g-funk"),
    G_HOUSE("g-house"),
    GANGSTER_RAP("gangster rap"),
    GARAGE_ROCK("garage rock"),
    GERMAN_HIP_HOP("german hip hop"),
    GERMAN_INDIE("german indie"),
    GERMAN_INDIE_POP("german indie pop"),
    GERMAN_POP("german pop"),
    GLAM_METAL("glam metal"),
    GLAM_ROCK("glam rock"),
    GNAWA("gnawa"),
    GOSPEL("gospel"),
    GOSPEL_R_AND_B("gospel r&b"),
    GOTHIC_ROCK("gothic rock"),
    GQOM("gqom"),
    GREGORIAN_CHANT("gregorian chant"),
    GRIME("grime"),
    GROOVE_METAL("groove metal"),
    GRUNGE("grunge"),
    GRUPERA("grupera"),
    HAPPY_HARDCORE("happy hardcore"),
    HARD_ROCK("hard rock"),
    HARD_TECHNO("hard techno"),
    HARDCORE_HIP_HOP("hardcore hip hop"),
    HARDCORE_TECHNO("hardcore techno"),
    HARDSTYLE("hardstyle"),
    HEAVY_METAL("heavy metal"),
    HI_NRG("hi-nrg"),
    HIGHLIFE("highlife"),
    HINDI_INDIE("hindi indie"),
    HINDI_POP("hindi pop"),
    HIP_HOP("hip hop"),
    HIP_HOUSE("hip house"),
    HIPDUT("hipdut"),
    HIPLIFE("hiplife"),
    HONKY_TONK("honky tonk"),
    HORRORCORE("horrorcore"),
    HOUSE("house"),
    HYPERPOP("hyperpop"),
    HYPERTECHNO("hypertechno"),
    IDM("idm"),
    INDIE("indie"),
    INDIE_FOLK("indie folk"),
    INDIE_POP("indie pop"),
    INDIE_PUNK("indie punk"),
    INDIE_R_AND_B("indie r&b"),
    INDIE_ROCK("indie rock"),
    INDIE_SOUL("indie soul"),
    INDONESIAN_HIP_HOP("indonesian hip hop"),
    INDONESIAN_INDIE("indonesian indie"),
    INDONESIAN_POP("indonesian pop"),
    INDONESIAN_R_AND_B("indonesian r&b"),
    INDUSTRIAL("industrial"),
    INDUSTRIAL_METAL("industrial metal"),
    INDUSTRIAL_ROCK("industrial rock"),
    ITALO_DANCE("italo dance"),
    J_POP("j-pop"),
    J_ROCK("j-rock"),
    JAM_BAND("jam band"),
    JANGLE_POP("jangle pop"),
    JAPANESE_CLASSICAL("japanese classical"),
    JAPANESE_VGM("japanese vgm"),
    JAZZ("jazz"),
    JAZZ_BLUES("jazz blues"),
    JAZZ_RAP("jazz rap"),
    JERSEY_CLUB("jersey club"),
    JUNGLE("jungle"),
    K_POP("k-pop"),
    KAYOKYOKU("kayokyoku"),
    KHALEEJI("khaleeji"),
    KRAUTROCK("krautrock"),
    LAGU_JAWA("lagu jawa"),
    LATIN("latin"),
    LATIN_ALTERNATIVE("latin alternative"),
    LATIN_HIP_HOP("latin hip hop"),
    LATIN_HOUSE("latin house"),
    LATIN_JAZZ("latin jazz"),
    LATIN_POP("latin pop"),
    LIQUID_FUNK("liquid funk"),
    LO_FI("lo-fi"),
    LO_FI_BEATS("lo-fi beats"),
    LO_FI_HIP_HOP("lo-fi hip hop"),
    LO_FI_HOUSE("lo-fi house"),
    LO_FI_INDIE("lo-fi indie"),
    LOUNGE("lounge"),
    MADCHESTER("madchester"),
    MAHRAGANAT("mahraganat"),
    MALAYALAM_HIP_HOP("malayalam hip hop"),
    MATH_ROCK("math rock"),
    MEDIEVAL("medieval"),
    MELBOURNE_BOUNCE("melbourne bounce"),
    MELODIC_BASS("melodic bass"),
    MELODIC_HOUSE("melodic house"),
    MELODIC_RAP("melodic rap"),
    METAL("metal"),
    METALCORE("metalcore"),
    MEXICAN_HIP_HOP("mexican hip hop"),
    MINIMALISM("minimalism"),
    MODERN_BLUES("modern blues"),
    MOOMBAHTON("moombahton"),
    MOROCCAN_POP("moroccan pop"),
    MOTOWN("motown"),
    MPB("mpb"),
    MUSICALS("musicals"),
    M_SICA_MEXICANA("música mexicana"),
    NATIVE_AMERICAN_MUSIC("native american music"),
    NEDERPOP("nederpop"),
    NEO_SOUL("neo soul"),
    NEO_PSYCHEDELIC("neo-psychedelic"),
    NEOCLASSICAL("neoclassical"),
    NEW_AGE("new age"),
    NEW_JACK_SWING("new jack swing"),
    NEW_RAVE("new rave"),
    NEW_WAVE("new wave"),
    NEW_YORK_DRILL("new york drill"),
    NEWGRASS("newgrass"),
    NIGERIAN_DRILL("nigerian drill"),
    NIGHTCORE("nightcore"),
    NOISE_ROCK("noise rock"),
    NORTE_O("norteño"),
    NORTHERN_SOUL("northern soul"),
    NORWEGIAN_POP("norwegian pop"),
    NOVA_MPB("nova mpb"),
    NU_DISCO("nu disco"),
    NU_JAZZ("nu jazz"),
    NU_METAL("nu metal"),
    OLD_SCHOOL_HIP_HOP("old school hip hop"),
    OPERA("opera"),
    ORCHESTRAL("orchestral"),
    ORGANIC_HOUSE("organic house"),
    OUTLAW_COUNTRY("outlaw country"),
    PHILLY_SOUL("philly soul"),
    PHONK("phonk"),
    PINOY_HIP_HOP("pinoy hip hop"),
    POP("pop"),
    POP_COUNTRY("pop country"),
    POP_PUNK("pop punk"),
    POP_ROCK("pop rock"),
    POP_SOUL("pop soul"),
    POP_URBAINE("pop urbaine"),
    POP_URBANO("pop urbano"),
    POST_DISCO("post-disco"),
    POST_GRUNGE("post-grunge"),
    POST_HARDCORE("post-hardcore"),
    POST_PUNK("post-punk"),
    POST_ROCK("post-rock"),
    POWER_METAL("power metal"),
    POWER_POP("power pop"),
    PROGRESSIVE_HOUSE("progressive house"),
    PROGRESSIVE_METAL("progressive metal"),
    PROGRESSIVE_ROCK("progressive rock"),
    PROGRESSIVE_TRANCE("progressive trance"),
    PROTO_PUNK("proto-punk"),
    PSYCHEDELIC_ROCK("psychedelic rock"),
    PSYCHOBILLY("psychobilly"),
    PSYTRANCE("psytrance"),
    PUNK("punk"),
    QUEERCORE("queercore"),
    QUIET_STORM("quiet storm"),
    R_AND_B("r&b"),
    R_AND_B_POP("r&b pop"),
    RAGE_RAP("rage rap"),
    RAGGA("ragga"),
    RALLY_HOUSE("rally house"),
    RANCHERA("ranchera"),
    RAP("rap"),
    RAP_METAL("rap metal"),
    RAP_ROCK("rap rock"),
    RED_DIRT("red dirt"),
    REGGAE("reggae"),
    REGGAE_ROCK("reggae rock"),
    REGGAETON("reggaeton"),
    REGGAETON_CHILENO("reggaeton chileno"),
    REGGAETON_MEXA("reggaeton mexa"),
    REQUIEM("requiem"),
    RIDDIM("riddim"),
    RIOT_GRRRL("riot grrrl"),
    ROCK("rock"),
    ROCK_AND_ROLL("rock and roll"),
    ROCKABILLY("rockabilly"),
    ROOTS_REGGAE("roots reggae"),
    ROOTS_ROCK("roots rock"),
    SAD_SIERRE_O("sad sierreño"),
    SAMBA("samba"),
    SCREAMO("screamo"),
    SEA_SHANTIES("sea shanties"),
    SEXY_DRILL("sexy drill"),
    SHATTA("shatta"),
    SHIBUYA_KEI("shibuya-kei"),
    SHOEGAZE("shoegaze"),
    SHOLAWAT("sholawat"),
    SIERRE_O("sierreño"),
    SINGER_SONGWRITER("singer-songwriter"),
    SKATE_PUNK("skate punk"),
    SLAP_HOUSE("slap house"),
    SLOWCORE("slowcore"),
    SLUDGE_METAL("sludge metal"),
    SOCA("soca"),
    SOFT_POP("soft pop"),
    SOFT_ROCK("soft rock"),
    SOUL("soul"),
    SOUL_JAZZ("soul jazz"),
    SOUNDTRACK("soundtrack"),
    SOUTHERN_GOTHIC("southern gothic"),
    SOUTHERN_HIP_HOP("southern hip hop"),
    SOUTHERN_ROCK("southern rock"),
    SPACE_MUSIC("space music"),
    SPACE_ROCK("space rock"),
    SPEED_METAL("speed metal"),
    SPOKEN_WORD("spoken word"),
    STONER_METAL("stoner metal"),
    STONER_ROCK("stoner rock"),
    STUTTER_HOUSE("stutter house"),
    SURF_ROCK("surf rock"),
    SWEDISH_POP("swedish pop"),
    SWING_MUSIC("swing music"),
    SYMPHONIC_METAL("symphonic metal"),
    SYNTHPOP("synthpop"),
    SYNTHWAVE("synthwave"),
    TECH_HOUSE("tech house"),
    TECHENGUE("techengue"),
    TECHNO("techno"),
    TEJANO("tejano"),
    TEKNO("tekno"),
    TEXAS_COUNTRY("texas country"),
    THRASH_METAL("thrash metal"),
    TRADITIONAL_COUNTRY("traditional country"),
    TRADITIONAL_FOLK("traditional folk"),
    TRANCE("trance"),
    TRAP("trap"),
    TRAP_FUNK("trap funk"),
    TRAP_LATINO("trap latino"),
    TRAP_METAL("trap metal"),
    TRAP_SOUL("trap soul"),
    TRIP_HOP("trip hop"),
    TROPICAL_HOUSE("tropical house"),
    UK_DRILL("uk drill"),
    UK_GARAGE("uk garage"),
    UK_GRIME("uk grime"),
    UNDERGROUND_HIP_HOP("underground hip hop"),
    URBANO_LATINO("urbano latino"),
    V_POP("v-pop"),
    VALLENATO("vallenato"),
    VAPORWAVE("vaporwave"),
    VARI_T_FRAN_AISE("variété française"),
    VIETNAMESE_HIP_HOP("vietnamese hip hop"),
    VILLANCICOS("villancicos"),
    VOCAL_JAZZ("vocal jazz"),
    WEST_COAST_HIP_HOP("west coast hip hop"),
    WITCH_HOUSE("witch house"),
    WORSHIP("worship"),
    YACHT_ROCK("yacht rock");

    private final String displayName;

    Genre(String displayName) {
        this.displayName = displayName;
    }

    @Override
    public String toString() {
        return displayName;
    }
}
